image: rust:latest

stages:
  - build

rust-latest:
  stage: build
  script:
    - apt-get update -y
    - apt-get install -y upx musl-tools
    - rustup target add x86_64-unknown-linux-musl
    - cargo rel
    - mv target/x86_64-unknown-linux-musl/release/esed esed
  artifacts:
    name: esed
    paths:
     - esed
